---
title: "Assignment 4"
author: "Fariha Khan"
date: '2017-10-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(gapminder))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(reshape2))
```

### Activity 1
#### Data reshaping cheatsheet
reshape2 Function    | tidyr Function 
---------------------|-------------------
`melt`               |  `gather`         
`dcast`              |  `spread`         

### Activity 2
Make a tibble with one row per year and columns for life expectancy for two or more countries.
Use knitr::kable() to make this table look pretty in your rendered homework.

```{r}
activ2 <- as.tibble(gapminder %>% 
      filter(country %in% c("Benin","Iceland","Mozambique",
                            "Sierra Leone","Venezuela", "Zambia")) %>% 
      group_by(country) %>% 
      select(country, year, lifeExp)) 

kable(activ2)

activ2 %>% 
      spread(country, lifeExp) %>% 
      kable()
```


